
package database_pro;

//import java.awt.*;
//import java.io.*;
import java.sql.*;
//import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
//import javax.imageio.ImageIO;
import javax.swing.*;

public class StRecord1 extends javax.swing.JFrame {
//define all my variables here for string and integer, and open database connection here-ref MObileStore
    String name,contact,courses,totalfee,pendfee,instpaid,instdate,ext_1,original_course,picture;
    int contact_i,totalfee_i,pendfee_i,instpaid_i,serialno;
    
    Connection conn;
    Statement st;
    void db(){
    try
      {
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/computer","root","");
        //  System.out.println("conn established");
        st=conn.createStatement();
        //  System.out.println("statement created");
      }
    catch(Exception e) 
      {
	System.out.println("Exception");
    }
    }
    public StRecord1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_contact = new javax.swing.JTextField();
        txt_courses = new javax.swing.JTextField();
        txt_tfee = new javax.swing.JTextField();
        txt_pfee = new javax.swing.JTextField();
        txt_inst = new javax.swing.JTextField();
        txt_date = new javax.swing.JTextField();
        btn_get_record = new javax.swing.JButton();
        btn_calculate = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        lbl_img = new javax.swing.JLabel();
        lbl_instdate = new javax.swing.JLabel();
        txt_instdate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Records");
        setLocation(new java.awt.Point(200, 200));
        setResizable(false);

        jLabel1.setText("Student Name:");
        jLabel1.setPreferredSize(new java.awt.Dimension(130, 20));

        jLabel2.setText("Student Contact:");

        jLabel3.setText("Courses:");

        jLabel4.setText("Total Fee:");

        jLabel5.setText("Pending Fee:");

        jLabel6.setText("Installement Paid:");

        jLabel7.setText("Current Date:");

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        txt_tfee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tfeeActionPerformed(evt);
            }
        });

        txt_inst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_instActionPerformed(evt);
            }
        });

        btn_get_record.setText("Get Record");
        btn_get_record.setToolTipText("Gets the record from database");
        btn_get_record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_get_recordActionPerformed(evt);
            }
        });

        btn_calculate.setText("Calculate");
        btn_calculate.setToolTipText("Calculates pending fee");
        btn_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calculateActionPerformed(evt);
            }
        });

        btn_update.setText("Update");
        btn_update.setToolTipText("Makes updates to database");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.setToolTipText("Deletes record from the database");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_exit.setText("Exit");
        btn_exit.setToolTipText("Exit this window");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        lbl_img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_instdate.setText("Due Date of Installment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_instdate, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_instdate))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_date))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_inst))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_pfee))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_tfee)
                                    .addComponent(txt_courses)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_contact))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_img, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_get_record, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_get_record, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txt_courses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tfee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_pfee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_inst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_instdate)
                            .addComponent(txt_instdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_img, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_tfeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tfeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tfeeActionPerformed

    private void txt_instActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_instActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_instActionPerformed

    private void btn_get_recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_get_recordActionPerformed
        // TODO add your handling code here:
        db();
       // System.out.println("inside record action");
        name=txt_name.getText();
        
        /*Correcting the inserted name*/
//        if(name.contains(" "))
//        {
//            /*getting names separately*/
//            int sp_index=name.indexOf(" ");
//            String first_name=name.substring(0, sp_index);
//            String last_name=name.substring(sp_index+1);
//            
//            
//            /*fixing first name*/
//            char name_initial=first_name.charAt(0);
//            String name_initial_str = Character.toString(name_initial);
//            String name_initial_str_cap=name_initial_str.toUpperCase();
//            String name_rest=first_name.substring(1, first_name.length());
//            first_name=name_initial_str_cap.concat(name_rest);
//            
//            /*fixing last name*/
//            char name_final=last_name.charAt(0);
//            String name_final_str = Character.toString(name_final);
//            String name_final_str_cap=name_final_str.toUpperCase();
//            String name_last_rest=last_name.substring(1,last_name.length());
//            last_name=name_final_str_cap.concat(name_last_rest);
//                        
//            
//            /*bringing together*/
//            name=first_name.concat(" ");
//            name=name.concat(last_name);
//                       
//            
//        }

        if(!name.contains(" "))
           {
            char name_initial=name.charAt(0);
            String name_initial_str = Character.toString(name_initial);
            String name_initial_str_cap=name_initial_str.toUpperCase();
            String name_rest=name.substring(1, name.length());
             name=name_initial_str_cap.concat(name_rest);
           }
      
        
        if(name.isEmpty())
           
        {
         JOptionPane.showMessageDialog(rootPane, "Please enter a name to begin!");
        }
        
        
        
        else
        {
            try {
                ResultSet rs=st.executeQuery("select * from regform");
                int count=0;
                //System.out.println("hi");
                while(rs.next())
                    {   
                        if(rs.getString("Full_Name").contains(name))
                        {
                        count++;
                        }
                       
                    }
                    
            if(count>1) {JOptionPane.showMessageDialog(rootPane, "More than one record found. Please enter Full Name.");}
            
            else if(count==1)
            {
                  // System.out.println(count);     
                ResultSet rs1=st.executeQuery("select * from regform");
                while(rs1.next())
                    {
                        if(rs1.getString("Full_Name").equalsIgnoreCase(name)||rs1.getString("Full_Name").contains(name))
                        {
                         
                         serialno=rs1.getInt("Serial_Number");
                     
                         txt_name.setText(rs1.getString("Full_Name"));
                         txt_contact.setText(rs1.getString("Contact"));
                     
                         totalfee_i=rs1.getInt("total_fee");
                         totalfee=Integer.toString(totalfee_i);
                         txt_tfee.setText(totalfee);
                     
                         pendfee_i=rs1.getInt("pending_fee");
                         pendfee=Integer.toString(pendfee_i);
                         txt_pfee.setText(pendfee);
     
                         courses=rs1.getString("Course");
                         txt_courses.setText(courses);
                     
                         picture=rs1.getString("Picture");
                        //ImageIcon pic = new ImageIcon("C:\\wamp\\www\\PHP_2016\\My Project - Original\\'"+picture+"'");
                       // ImageIcon pic = new ImageIcon("'"+picture+"'");
                       // lbl_img.setIcon(pic);
                     
                              if(rs1.getString("Date_Installment").isEmpty())
                                 {
                                        
                                       SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                                       Calendar c = Calendar.getInstance();
                                       String date1 = sdf.format(c.getTime());
                                       txt_date.setText(date1); 
                                       c.add(Calendar.DATE, 30); // Adding 30 days
                                       String date2 = sdf.format(c.getTime());
                                       txt_instdate.setText(date2);
                   
                                 }
                              else
                                 {
                                     String date2=rs1.getString("Date_Installment");
                                     txt_instdate.setText(date2);
                                     SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                                     Calendar c = Calendar.getInstance();
                                     String date_c = sdf.format(c.getTime());
                                     txt_date.setText(date_c);
                                     //System.out.println(date_c);
                                     if(date2.equals(date_c))
                                     {
                                       JOptionPane.showMessageDialog(rootPane, "Installment due today");  
                                     }
                                 }
                   
                        }
                      }
                    }
                }
            
            catch (SQLException ex) {
                Logger.getLogger(StRecords.class.getName()).log(Level.SEVERE, null, ex);
                                    } 

        }
    }//GEN-LAST:event_btn_get_recordActionPerformed

    private void btn_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calculateActionPerformed
        // TODO add your handling code here:
        totalfee=txt_tfee.getText();
        pendfee=txt_pfee.getText(); 
        instpaid=txt_inst.getText();
        
        
        instpaid_i=Integer.parseInt(instpaid);
        pendfee_i=Integer.parseInt(pendfee);
        pendfee_i=pendfee_i-instpaid_i;
        pendfee=Integer.toString(pendfee_i);
        txt_pfee.setText(pendfee);
        
    }//GEN-LAST:event_btn_calculateActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        db();
        name=txt_name.getText();
        contact=txt_contact.getText();
        courses=txt_courses.getText();
        totalfee=txt_tfee.getText();
        pendfee=txt_pfee.getText();  
        instdate=txt_instdate.getText();
        
        //admin will have to manually then change the total fee text field by addition/subtraction
        totalfee=txt_tfee.getText();
        pendfee=txt_pfee.getText();
        try {
            st.executeUpdate("update regform set Full_Name='"+name+"',Contact='"+contact+"',Course='"+courses+"',total_fee='"+totalfee+"',pending_fee='"+pendfee+"',Date_Installment='"+instdate+"' where Serial_Number='"+serialno+"'");
            JOptionPane.showMessageDialog(rootPane, "Records have been updated!");
           
        }
        catch (SQLException ex) {
            Logger.getLogger(StRecords.class.getName()).log(Level.SEVERE, null, ex);
                                }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        db();
        try {
            st.execute("delete from regform where Serial_Number='"+serialno+"'");
           JOptionPane.showMessageDialog(rootPane, "Records have been deleted!");
            }
        catch (SQLException ex) {
            Logger.getLogger(StRecords.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StRecord1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StRecord1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StRecord1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StRecord1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StRecord1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calculate;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_get_record;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JLabel lbl_instdate;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_courses;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_inst;
    private javax.swing.JTextField txt_instdate;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_pfee;
    private javax.swing.JTextField txt_tfee;
    // End of variables declaration//GEN-END:variables
}
